#
# Copyright 2012-2019 CNRS-UM LIRMM, CNRS-AIST JRL
#

dist: xenial
addons:
  apt:
    packages:
    - doxygen
    - doxygen-latex
    - libboost-all-dev
    - libeigen3-dev
    - python-pip
    - python3-pip
    - cython
    - python-nose
    - python-numpy
    - python-coverage
    - cython3
    - python3-nose
    - python3-numpy
    - python3-coverage
    - python3-setuptools
branches:
  except:
    - debian
language: cpp
compiler:
- gcc
- clang
env:
  global:
  - APT_DEPENDENCIES=""
  - GIT_DEPENDENCIES="jrl-umi3218/Eigen3ToPython jrl-umi3218/SpaceVecAlg"
  - GH_USERNAME=gergondet
  - GH_REPO=jrl-umi3218/RBDyn
  - secure: FCe7ktcmBJWgEFsCBnG1QfIhkgNKM3uyRMS9mXiY8hfGQ9KGj/9X4qebUmfZ1ay6Rw2B22FXpRiJk2GmsHxo1RZH3f27b6F1mWz25RgJGX986k2nPChCshf5gORfMI5BKksyXFzp24sXBLcYKGz/xrOioSUY1wPJ3JZ7r7kDEV4=
  - CMAKE_ADDITIONAL_OPTIONS="-DPYTHON_BINDING_BUILD_PYTHON2_AND_PYTHON3:BOOL=ON -DPYTHON_BINDING_USER_INSTALL:BOOL=ON"
  matrix:
    - CMAKE_BUILD_TYPE=RelWithDebInfo
    - CMAKE_BUILD_TYPE=Debug
notifications:
  slack:
    rooms:
      secure: N2C/Q9nr/TNjVE1UIRhT7gXN6bfJCe1nH7FIMA0RrANsdGkGsJHhuJsiOs8cUE7ozRFSiZ/ewMSADqItfwwp692pI1wp2y0X8wxRMB3pmo01Owv7on6NgLHXY4Br6peCSwGem3MaywcN8QaBlPxNVXFTfGi39GDvA8szLkCGHGw=
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install:
- export CMAKE_ADDITIONAL_OPTIONS="${CMAKE_ADDITIONAL_OPTIONS} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
- ./.travis/run  before_install
